#file: noinspection undefined
spring:
  main:
    web-application-type: reactive
  application:
    name: XLG-DGL-GATEWAY-SERVICE
server:
  port: 8888
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
