#file: noinspection undefined
spring:
  application:
    name: SERVICE-GRAPHQL-CLIENT
server:
  port: 8088
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}